# Generated by Django 2.2.1 on 2019-06-05 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='image_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=2034),
            preserve_default=False,
        ),
    ]
